### ISSUE TITLE
VisualRepresenation.java - Add Method

### ISSUE THREAD

**Issue by RelativeForce** [RelativeForce/CS2010#1]
Please create `setImage(int x, int y, Integer[][] image)`

In this method, `image` is a 2D array that holds RGB values that can be used to display on the screen. `x` and `y` are the position that this image will have relative to (0,0) which is the top-left of the `Board` image. Some of the elements in `image` will be `null`, This means that there is no pixel at this location to be displayed. Some images may be overlays (hues that will be placed over countries to show ownership). The `VisualRepresenation` should store these parameters as fields.

**Comment by RelativeForce** [comment]
The current implementation of `setImage()` does not initialise `x` or `y`.

**Comment by Necrogear** [comment]
Implementation now initialises x and y.
