### ISSUE TITLE
Alter Player.java

### ISSUE THREAD

**Issue by RelativeForce** [RelativeForce/CS2010#13]
Change `Player` to a class. So the different players are `static` instances of the class. Other than that the class should remain the same. Also, there is no need for `equals()` as the object references should be enough.

**Comment by RelativeForce** [comment]
Could you please add `getColor()` to `Player.java`

**Comment by Klei20** [comment]
Things to do:
1. Add another `Army` field to the `Player`  class
2. Add set and get methods to both `Army` fields in `Player`
