### ISSUE TITLE
Bug for the dice roll, chosen dices are in reverse order

### ISSUE THREAD

**Issue by djsnackbar** [RelativeForce/CS2010#40]
Possible location :
WAR MENU CLASS in the 
DICE ROLL METHOD. 
From lines 312 the logic doesn't seem correct.  

Issue : When you select 1 dice it is actually picking 3 dices, and vice versa for 3 dices actually being 1 dice.  
Extra reason: Currently 1 dice is gives you higher chance of winning than 3 dice due to this bug.

**Comment by RelativeForce** [comment]
This bug is fixed. Dice are now ordered correctly
