### ISSUE TITLE
"Challenges" does not work with any other player other than Player 1.

### ISSUE THREAD

**Issue by adrianw17** [RelativeForce/CS2010#41]
The logic and implementation is currently in `challenge.java`

I can reproduce by following these steps:
1. Start the app by clicking on the run icon in Eclipse.
2. Select the map, and the number and players to load the game.
3. Player 1 starts by adding troops to any country, Player 1 will then complete a challenge - rewarding plus ten troops. Then if another player does the exact same as Player 1 - they will not complete the challenge.

Actual Results: Player 1 will complete the challenge, other players will not complete the challenge.
Expected Results: Player 1 and other players to complete the exact same challenge.

**Comment by adrianw17** [comment]
@Klei20 has experienced this bug too.

**Comment by adrianw17** [comment]
#40 Another bug

**Comment by RelativeForce** [comment]
Challenges are now map specific at which prevents this bug from happening. It was caused by all the maps having the same challenges but the challenges were easily completed on the larger maps.
