### ISSUE TITLE
Allow the website to be adjusted for different screen widths using media tags.

### ISSUE THREAD

**Issue by mcgirlja** [RelativeForce/CS2010#42]
**Summary:**
Our website is not designed for different screen widths. When you reduce the width of the screen, some of the links disappear and some information overlaps.
**Steps to reproduce:**
1. Open: https://hannahmiller98.github.io/
2. Reduce the width of the screen to a number of sizes and check information is missing/overlapping.
3. Reduce screen width to the smallest 

**Expected Result**

- Website is meant to look the same but at a smaller screen width

**Actual Result**

- The navigation bar links disappear and some information overlaps onto images

**How to:**

Edit homepage.css using @media queries so that the screen is adjusted for different screen widths.

**Comment by mcgirlja** [comment]
@HannahMiller98 #33 

Adding the navigation bar is an essential step to website layout and interaction with media tags.

**Comment by RelativeForce** [comment]
The website adapts to a variety of screen sizes from mobile to 4K
