### ISSUE TITLE
Visual Effects - Environmental Hazard

### ISSUE THREAD

**Issue by Klei20** [RelativeForce/CS2010#43]
**Description:**

The visual effects for the environmental hazards do not appear on the map when they are active. Classes involved: 'EnvironmentalHazard', 'Animation'.

**To Reproduce:**

1. Start Game.
2. End each player's turn.
3. Start a new round.

**Expected Result:**

Visual Effects for each Environmental Hazard on the screen should display.

**Observed Result:**

No Visual Effects for Environmental Hazards seen.

**Comment by RelativeForce** [comment]
Environmental Hazards appear on the screen.
