### ISSUE TITLE
Sound Effects - Combat

### ISSUE THREAD

**Issue by Klei20** [RelativeForce/CS2010#44]
**Description:**

There are no sound effects playing during the combat phase when another country attacks another.
Classes involved: 'CombatState', 'SoundEffect'.

**To Reproduce:**

1. Start Game.
2. Cycle through first Player's phase until Combat Phase is reached.
3. Attack a Country in Combat Phase.

**Expected Result:**

Sound effect is played when the current Player's Country attacks another.

**Observed Result:**

No Sound effect is played when the current Player's Country attacks another.

**Comment by RelativeForce** [comment]
Removed as this was a test issue for the git lab session.
