### ISSUE TITLE
Redesign and implement a game winning screen.

### ISSUE THREAD

**Issue by adrianw17** [RelativeForce/CS2010#48]
The game winning screen is the screen that will appear to the players when the game is over. The game is over when one player has dominated all of the countries. At the moment the game winning screen is just a black screen and displaying "Winner = Player X", X being the player number of the winner. This current implementation stored in `endState.java`

Therefore, the enhancement is to create a "game winning display" at 1920 x 1080 resolution and name it `gameWinningScreen.png` on Photoshop. This design should follow the game's house style. And then put this into the folder: "ui/assests".

So once this is implemented, this new design will be shown to the players, rather than displaying a black screen.

**Comment by RelativeForce** [comment]
The winning screen now shows a podium that the players appear on in the order they were knocked out of the game. The winning player is on top of the podium.
