### ISSUE TITLE
Add an "about" for each state

### ISSUE THREAD

**Issue by djsnackbar** [RelativeForce/CS2010#50]
Currently SetUpState has an about which will explain to the user how to play the game in the current state when the H key is pressed. This can be reused to be done to the other states.

How to do: 
                   -Copy template from SETUP STATE CLASS from lines 48 to 56
                   -reuse code in COMBAT STATE,  REINFORCEMENT STATE.

**Comment by RelativeForce** [comment]
This has been completed for all game states.
