### ISSUE TITLE
Allow the panning boundaries to be activated when the cursor is further to the edge of the screen

### ISSUE THREAD

**Issue by mcgirlja** [RelativeForce/CS2010#51]
**Summary**
When panning around the map, the user has to put his/her cursor to the edge of the screen, although the boundaries on which this occurs is too large, causing the screen to move around when the cursor is not as close to the edge as the user intended.
**Steps to reproduce**

1. Open eclipse
2. Run the game
3. Move cursor near the edge

**Expected Result**

- User expects the screen to pan around when the cursor is right next to the edge of the screen

**Actual Result**

- Even when the cursor is not at the edge of the screen, it pans around the map when it's close enough, therefore the boundaries in which this occurs need to be reduced. 

**How to fix**

Reduce boundary percentage in the panning() method to below 5% in the CoreGameState.java class.

**Comment by RelativeForce** [comment]
Cursor now activates when in the edge 5% of the screen, was 10%.
