### ISSUE TITLE
Implement CombatHandler.java

### ISSUE THREAD

**Issue by RelativeForce** [RelativeForce/CS2010#9]
Create and write `CombatHandler.java` according to the UML.
[https://creately.com/diagram/j8obaup31/k2ytzNjGlHff3HltJTc6lgqKq0%3D](url)

**Comment by Klei20** [comment]
Things to do:
1. Create test class for `CombatHandler`
2. Allow `CombatHandler` to be constructed with a `SEED`
3. Add better comments to CombatHandler
4. Finish off `fight()` method
